### ISSUE TITLE
HUD display method

### ISSUE THREAD

**Issue by fiveangle** [ppamidimarri/TeslaModel3HUD#1]
Interesting project ! Thanks for sharing it. 

Curious, but have you considered pre-contouring the display then use the model 3 windshield as the display surface ? The windshield could be augmented with cling material for the silvering similar to how Garmin does:

https://www.gps4us.com/GARMIN-HUD-Windshield-film--P3148.html

I would imagine this may dramatically improve the aesthetics ?

-=dave

**Comment by ppamidimarri** [comment]
I tried displaying it on the windshield and it didn't work unless the display was very close to the windshield, which looked worse with wires running around on the dash. I don't know how to contour the display, if I get that dialed in just right, it might work.
